server:
  port: 8778

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#服务的名称
spring:
  application:
    name: product-service

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
env: test2019
branch: master
